In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/home/kifaru/projects/data-viz/Data/sacco.csv")

In [3]:
df.head()

,member_id,full_name,age,county,employment_sector,employer_name,monthly_contribution,date_joined,phone_number,gender,member_status,remarks
0,SACCO-0001,Kamau Mutua,28yrs,Marsabit,Agriculture,East African Breweries,"KES 23,795",Feb-2015,2.547678e+11,Female,ACTIVE,NaN
1,SACCO-0002,Salome Nyambura,22 years,Uasin Gishu,Transport,Absa Kenya,NaN,2017-04,7.451770e+08,F,Inactive,NaN
2,SACCO-0003,OWINO Kiptoo,29,Siaya,Agriculture,Bamburi Cement,NaN,06/2024,7.945660e+08,Female,inactive,NaN
3,SACCO-0004,Odhiambo sigei,62,Uasin Gishu,Trade,Cooperative Bank,76575,2019-12,7.869778e+08,Female,active,NaN
4,SACCO-0005,Mercy Lagat,57,Narok,ICT,World Vision Kenya,4272.0,2018-01,7.538434e+08,M,INACTIVE,NaN

In [4]:
#df.to_excel("/home/kifaru/Desktop/sacco.xlsx")

In [5]:
df.describe()

       phone_number
count  8.430000e+02
mean   1.257913e+11
std    1.270606e+11
min    7.003443e+08
25%    7.476000e+08
50%    7.983646e+08
75%    2.547481e+11
max    2.547997e+11

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   member_id             1000 non-null   str
 1   full_name             1000 non-null   str
 2   age                   950 non-null    str
 3   county                1000 non-null   str
 4   employment_sector     1000 non-null   str
 5   employer_name         895 non-null    str
 6   monthly_contribution  800 non-null    str
 7   date_joined           1000 non-null   str
 8   phone_number          843 non-null    float64
 9   gender                1000 non-null   str
 10  member_status         1000 non-null   str
 11  remarks               28 non-null     str
dtypes: float64(1), str(11)
memory usage: 93.9 KB

In [7]:
df_clean = df.replace(" " ,np.nan)

In [8]:
df_clean.head()

,member_id,full_name,age,county,employment_sector,employer_name,monthly_contribution,date_joined,phone_number,gender,member_status,remarks
0,SACCO-0001,Kamau Mutua,28yrs,Marsabit,Agriculture,East African Breweries,"KES 23,795",Feb-2015,2.547678e+11,Female,ACTIVE,NaN
1,SACCO-0002,Salome Nyambura,22 years,Uasin Gishu,Transport,Absa Kenya,NaN,2017-04,7.451770e+08,F,Inactive,NaN
2,SACCO-0003,OWINO Kiptoo,29,Siaya,Agriculture,Bamburi Cement,NaN,06/2024,7.945660e+08,Female,inactive,NaN
3,SACCO-0004,Odhiambo sigei,62,Uasin Gishu,Trade,Cooperative Bank,76575,2019-12,7.869778e+08,Female,active,NaN
4,SACCO-0005,Mercy Lagat,57,Narok,ICT,World Vision Kenya,4272.0,2018-01,7.538434e+08,M,INACTIVE,NaN

In [11]:
#finding the sum of the missing values
df_clean.isnull().sum()

member_id                 0
full_name                 0
age                      50
county                    0
employment_sector         0
employer_name           105
monthly_contribution    200
date_joined               0
phone_number            157
gender                    0
member_status             0
remarks                 972
dtype: int64

In [30]:
missing_data = df[["age","employer_name","monthly_contribution","phone_number","remarks"]].isnull().sum()
print(missing_data)

age                      50
employer_name           105
monthly_contribution    200
phone_number            157
remarks                 972
dtype: int64

In [33]:
original_data = len(df)
print(original_data)

1000

In [41]:
#finding the percentage of each column missing
percentage_missing = missing_data / original_data *100
print(percentage_missing.round(2).astype(str) + "%")

age                      5.0%
employer_name           10.5%
monthly_contribution    20.0%
phone_number            15.7%
remarks                 97.2%
dtype: str

In [53]:
df["member_id"].duplicated().sum()

np.int64(30)