In [3]:
import pandas as pd
import numpy as np

data = {
    "patient_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "age": [25, 34, "?", 67, 45, 29, 52, "?", 38, 61],
    "appointment_date": [
        "2026-08-01",
        "2026-08-01",
        "?",
        "2026-08-02",
        "2026-08-02",
        "?",
        "2026-08-03",
        "2026-08-03",
        "2026-08-04",
        "?"
    ],
    "department": [
        "Dental",
        "Cardiology",
        "General",
        "?",
        "Dental",
        "General",
        "Cardiology",
        "?",
        "Dental",
        "General"
    ],
    "appointment_status": [
        "Attended",
        "Missed",
        "Attended",
        "?",
        "Attended",
        "Missed",
        "Attended",
        "Attended",
        "?",
        "Missed"
    ]
}

df = pd.DataFrame(data)

In [4]:
#Display the first 5 rows
df.head(5)

   patient_id age appointment_date  department appointment_status
0         101  25       2026-08-01      Dental           Attended
1         102  34       2026-08-01  Cardiology             Missed
2         103   ?                ?     General           Attended
3         104  67       2026-08-02           ?                  ?
4         105  45       2026-08-02      Dental           Attended

In [5]:
#Finding the number of rows and columns
df.shape

(10, 5)

In [6]:
df.dtypes
#age is not numerical as it contains '?' ,thus pandas treats it as an object

patient_id             int64
age                   object
appointment_date         str
department               str
appointment_status       str
dtype: object

In [7]:
#identifing missing data
df_clean = df.replace("?",np.nan)

In [8]:
#count missing values in each column
df_clean.isna().sum()
#appointment_date is the column with the most missing data
#patient_id has no missing data

patient_id            0
age                   2
appointment_date      3
department            2
appointment_status    2
dtype: int64

In [9]:
#Removing records where appointment data is missing
df = df_clean.dropna(subset=["appointment_date"] , axis=0)

In [11]:
#number of records before cleaning is
Original_records = len(df_clean)
print(f"len:{Original_records:.2f}")

len:10.00

In [12]:
#number of records after cleaning is 
Cleaned_records = len(df)
print(f"len:{Cleaned_records:.2f}")

len:7.00

In [13]:
#number of records removed is 
Records_removed = Original_records - Cleaned_records
print(f"Records removed:{Records_removed}")

Records removed:3

In [14]:
df.head(7)

   patient_id  age appointment_date  department appointment_status
0         101   25       2026-08-01      Dental           Attended
1         102   34       2026-08-01  Cardiology             Missed
3         104   67       2026-08-02         NaN                NaN
4         105   45       2026-08-02      Dental           Attended
6         107   52       2026-08-03  Cardiology           Attended
7         108  NaN       2026-08-03         NaN           Attended
8         109   38       2026-08-04      Dental                NaN

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          7 non-null      int64
 1   age                 6 non-null      object
 2   appointment_date    7 non-null      str
 3   department          5 non-null      str
 4   appointment_status  5 non-null      str
dtypes: int64(1), object(1), str(3)
memory usage: 336.0+ bytes

In [16]:
#Percentage of records removed
Percentage_removed = ( Records_removed / Original_records) *100

In [18]:
print(f"Removed_records={Records_removed}")
print(f"Percentage_removed={Percentage_removed:.2f}%")

Removed_records=3
Percentage_removed=30.00%